### ISSUE TITLE
Offset table disappears when a previously saved model is loaded

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#82] opened 2023-03-08 14:48 UTC
[2023-03-08_15_46_22_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/10921706/2023-03-08_15_46_22_fruitsModel.zip)

When a previously saved model is loaded, the offset table gets empty. This was observed on beta version 23.2.4.2.

@arunge

**Comment by arunge** [comment] 2023-03-09 18:51
The offset table of the data that you provided was empty:

![image](https://user-images.githubusercontent.com/16759098/223984245-eebb3779-0a2c-4fcc-a005-33067ebb4dbe.png)

Thus nothing could be updated. I tested the download and upload of example data that contains offset data, all works as expected:

![image](https://user-images.githubusercontent.com/16759098/223984750-7eae3b36-40a4-45b2-98a5-ffe30a7c8b66.png)

However, there is an issue with the update of tables when using "enter" to submit values. Maybe this was the cause that the offset table of your saved data did not contain any values. The fix will be available soon. Currently, we are trying to use the most recent version of shinyMatrix that contains [another bug fix](https://github.com/INWTlab/shiny-matrix/issues/30#issuecomment-1379117189). I will notify you when this will be online.

**Comment by arunge** [comment] 2023-03-15 17:25
This should be fixed with [version 23.03.2](https://github.com/Pandora-IsoMemo/resources/pull/84) on [beta](https://isomemoapp.com/app/resources-beta).

**Closed by arunge** 2023-03-15 17:25 UTC
Labels: bug, ReSources App, 2022-WP2-7
