### ISSUE TITLE
ReSources (BETA) Bug: Model saved files are empty and app crashes after running

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#16] opened 2022-05-20 12:47 UTC
Hi @arunge ,
So I created a model in ReSources (Beta) and I saved it using the Download button on the right side. I saved it at different steps. However, I then tried running the model and the app crashed after running smoothly. So I loaded again the saved models and I found out that these were empty.

That model was identical to the other one I have now attached (Full Model). This time instead, the saving process worked perfectly. 
However, I still face the same crashing issue after running the model.

[Full Model.zip](https://github.com/Pandora-IsoMemo/resources/files/8740162/Full.Model.zip)
[Empty Model.zip](https://github.com/Pandora-IsoMemo/resources/files/8740163/Empty.Model.zip)

**Comment by CarloCocozza** [comment] 2022-05-20 13:25
I recreated the same model in the normal online version of ReSources and I still face the same crashing problem. 
Moreover, I did this also offline via R and this is what I receive as error:

![Bug Offline Version](https://user-images.githubusercontent.com/101706974/169537291-68741a82-e2a4-4851-8de4-565979506f81.PNG)

**Comment by arunge** [comment] 2022-05-20 13:58
@CarloCocozza Thanks for reporting this bug. I will look into it soon.

**Comment by arunge** [comment] 2022-05-23 19:04
@mgross I tried to fix the bug, but when fixing one error, another occurs. Since, it would take me quite long to understand all your transformations, such that I could fix the bug, could you have a look and find the reason?

I extracted the part of the code that produces the error into a function
https://github.com/Pandora-IsoMemo/resources/blob/da962772145ae38805fe3fcb4dac6920643685fc/R/04-modelSummary.R#L452
and wrote tests for it: https://github.com/Pandora-IsoMemo/resources/blob/bug/16_appCrashesAfterUpload/tests/testthat/test-04-modelSummary.R
The function is working with the app's example data, but fails with the data from @CarloCocozza (where I believe user estimates are specified). Could you read the details in https://github.com/Pandora-IsoMemo/resources/pull/18#issue-1245550835 and fix the bug on the branch `bug/16_appCrashesAfterUpload`? If the tests succeed the bug should be fixed...
If you have any question, just contact me.
Thanks in advance! :slightly_smiling_face:

**Comment by arunge** [comment] 2022-05-23 19:06
@CarloCocozza Do you mean with
> I saved it at different steps.

different model specifications?

Is the bug described in https://github.com/Pandora-IsoMemo/resources/pull/18#issue-1245550835 the one you found?
I could not reproduce your error message.

**Comment by CarloCocozza** [comment] 2022-05-23 19:07
Dear @arunge and @mgross ,

As a follow up, I have also tried by removing user estimates and prior. The bug is still present for that model.

Additionally, I report that when I removed user estimates from that previously saved model, user groups could not be removed (although they were empty). I attach a screenshot of this.

![BUg group estimates](https://user-images.githubusercontent.com/101706974/169889195-55a81d32-2ced-4b60-af6e-1da660dd733a.PNG)

**Comment by CarloCocozza** [comment] 2022-05-23 19:10
> @CarloCocozza Do you mean with
> 
> > I saved it at different steps.
> 
> different model specifications?
> 
> Is the bug described in [#18 (comment)](https://github.com/Pandora-IsoMemo/resources/pull/18#issue-1245550835) the one you found? I could not reproduce your error message.

I meant that I saved the same model more times when I was building it. So I saved a model after building the data, then I saved an updated version when building the priors and so on. It was just a way to be sure that, if the model crashed suddenly, I should not have started from the beginning. This was done in the same session of model building (so to be clear, I did not close the app and then started from the same saved model in a second moment).

**Comment by mgross** [comment] 2022-05-27 09:30
I will look on Monday into this.

**Comment by mgross** [comment] 2022-05-30 10:01
@arunge I created a new pull request:
https://github.com/Pandora-IsoMemo/resources/pull/20 
That should solve the issue

**Comment by arunge** [comment] 2022-05-30 12:10
@mgross Thanks! I will check your fix and return to you in case of questions. If all is solved, I will merge it to the beta version.

**Comment by arunge** [comment] 2022-05-30 15:14
@CarloCocozza We fixed the bug with the `fullData.zip` file with version 22.5.1, for details see 
- https://github.com/Pandora-IsoMemo/resources/pull/18#issue-1245550835

With version 22.5.2 I added the option to down- and upload model objects that do contain only the model inputs but not the model ouptut, for details see
- https://github.com/Pandora-IsoMemo/resources/pull/19#issue-1248163022

Now it is possible to upload `Full.Model.zip` and `Empty.Model.zip` and the app is not crashing.

Is there any other issue here?

**Comment by arunge** [comment] 2022-06-02 13:02
@CarloCocozza With version 22.5.3. of the **beta** app the issue with removing user estimates mentioned in https://github.com/Pandora-IsoMemo/resources/issues/16#issuecomment-1135039149 should be fixed.

Regarding:
> As a follow up, I have also tried by removing user estimates and prior. The bug is still present for that model.

Is there any bug in the "Prior Info" tab? Or is everything fixed now?

**Comment by arunge** [comment] 2022-06-02 13:17
@isomemo the bug fixes mentionend in this issue are currently only available for the **beta** version because some fixes require the up/download functionality of model objects.

Should we merge the current beta version into the main version? Besides the bug fixes, we would add the following features to the main:
- updated version of the oxcal output: https://github.com/Pandora-IsoMemo/resources/issues/7
- up/download of model objects: https://github.com/Pandora-IsoMemo/resources/issues/6

Or should we wait until we finish the update of the UI: https://github.com/Pandora-IsoMemo/resources/issues/23 ??

**Comment by isomemo** [comment] 2022-06-02 13:23
If there is no additional work for doing two mergers please go ahead and do a merger now.

**Comment by arunge** [comment] 2022-06-02 13:43
Ok, thanks @CarloCocozza for helping here!

**Closed by arunge** 2022-06-02 13:43 UTC
Labels: bug, Support: Bug fixing
